# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mixing Apprentice 🎧 Krishna Bhamidipati
email: 
description: >- # this means to ignore newlines until "baseurl:"
  Personal journal of learing how to record, mix and master music. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://krishna.studio" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  NaanProphet

# Build settings
markdown: kramdown
theme: minima

# Plugin settings
algolia:
  application_id: JOFZZNAMVA
  index_name:     krishnastudio
  search_only_api_key: 0f824a967919eae8798349b6a34013f4
target-blank:
  add_css_classes: ext-link
