baseURL = 'https://krishna.studio/'
languageCode = 'en-us'
title = 'Krishna Bhamidipati'
theme = 'hugo-theme-stack'
cleanDestinationDir = true

summaryLength = 70

# [Params]
# # description = 'Not falling for it'
# favicon = 'favicon.ico'


[module.hugoVersion]
extended = true
min = "0.87.0"

[pagination]
pagerSize = 10

[params]
mainSections = [ "post" ]
featuredImageField = "image"
rssFullContent = true

[params.footer]
since = 2016
customText = "Krishna Bhamidipati"

[params.dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 EST"

[params.sidebar]
emoji = "👀"
subtitle = "Keep Asking How"
compact = false

[params.sidebar.avatar]
enabled = true
local = true
src = "img/avatar.png"

[params.article]
headingAnchor = false
math = false
toc = true
readingTime = true

[params.article.license]
enabled = false
default = "Licensed under CC BY-NC-SA 4.0"

[[params.widgets.homepage]]
type = 'archives'

[[params.widgets.homepage]]
type = 'categories'

[[params.widgets.homepage]]
type = 'tag-cloud'

[params.widgets.homepage.params]
limit = 20

# [[params.widgets.homepage]]
# type = 'search'

[[params.widgets.page]]
type = 'toc'

[params.colorScheme]
toggle = true
default = "auto"

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = false
